spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect


  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb